name: Create Release for Master

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Use Node.js 12.x
          uses: actions/setup-node@v1
          with:
            node-version: 12.x

        - name: Restore npm cache
          uses: actions/cache@v2
          id: cache
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        - name: Install dependencies
          run: npm ci

        - name: Run Linter
          run: npm run lint

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Changelog
        id: changelog
        run: |
            echo "::set-output name=result::$(npx conventional-changelog-cli -p angular -u -r)"

      - name: Extract tag name
        id: tag
        uses: tyankatsu0105/read-package-version-actions@v1

      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.deploy_access_token }}
        with:
          tag_name: ${{ steps.tag.outputs.version }}
          release_name: ${{ steps.tag.outputs.version }}
          body: |
              ${{ steps.changelog.outputs.result }}
          draft: false
          prerelease: false
