name: Create Release for Master

on:
  push:
    branches: [master]

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Generate Changelog
              uses: ScottBrenner/generate-changelog-action@1.0.0
              id: Changelog
              env:
                REPO: ${{ github.repository }}

            - name: Extract tag name
              id: tag
              uses: actions/github-script@v2
              with:
                github-token: ${{ secrets.deploy_access_token }}
                script: |
                  return context.payload.ref.replace(/\/refs\/tags\//, '');

            - name: Create Release
              uses: actions/create-release@latest
              env:
                GITHUB_TOKEN: ${{ secrets.deploy_access_token }}
              with:
                tag_name: ${{ steps.tag.outputs.result }}
                release_name: ${{ steps.tag.outputs.result }}
                body: |
                    ${{ steps.Changelog.outputs.changelog }}
                draft: false
                prerelease: false
